version: "3.5"

services:
  mariadb:
    image: "mariadb:10.7.3"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      # - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
      - database:/var/lib/mysql # Use bind mount

  drupal:
    build:
      context: .
      dockerfile: docker/apache/Dockerfile
    ports:
      - 8080:80
    environment:
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
      COMPOSER_MEMORY_LIMIT: -1
    restart: always

volumes:
  database:
